version: 2
jobs:
  test-go-1-12:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y bzr
      - run: make TEST_FLAGS="-timeout 60s -race -v" test
  test-go-1-13:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: sudo apt-get install -y bzr
      - run: make TEST_FLAGS="-timeout 60s -coverprofile cover.out -race -v" test
  test-go-1-15:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: sudo apt-get install -y bzr
      - run: make TEST_FLAGS="-timeout 60s -coverprofile cover.out -race -v" test
workflows:
  version: 2
  testing:
    jobs:
      - test-go-1-13
      - test-go-1-15
